ForExercising/Models/ErrorViewModel.cs
using System;

namespace ForExercising.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ForExercising/ViewModels/AddYuGiOhCardViewModel.cs
using ForExercising.CustomModelValidations;
using ForExercising.ViewModels.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ForExercising.ViewModels
{
    public class AddYuGiOhCardViewModel : IValidatableObject
    {
        [Required]
        [MinLength(3)]
        [MaxLength(30)]
        public string Name { get; set; }

        public MonsterAttribute Attribute { get; set; }

        [Range(1, 12)]
        public int Level { get; set; }

        [Required]
        [Url]
        public string Artwork { get; set; }

        public MonsterType Type { get; set; }

        [Required]
        [MinLength(20)]
        [MaxLength(200)]
        public string Description { get; set; }

        [Range(0, 5000)]
        public int Attack { get; set; }

        [Range(0, 5000)]
        public int Defense { get; set; }

        [Display(Name ="Date of creation")]
        [IsBeforeCurrentDate]
        [DataType(DataType.Date)]
        public DateTime CreatedOn { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Attack + Defense > 9000)
            {
                yield return new ValidationResult("Sum of the Attack and Defense cannot be more than 9000");
            }

            if (CreatedOn.Year<1900)
            {
                yield return new ValidationResult("The year of creation shoud be after 1900");
            }
        }
    }
}

ForExercising/ViewModels/Enums/MonsterAttribute.cs
namespace ForExercising.ViewModels.Enums
{
    public enum MonsterAttribute
    {
        DARK, 
        EARTH, 
        FIRE, 
        LIGHT, 
        WATER, 
        WIND
    }
}

ForExercising/ViewModels/Enums/MonsterType.cs
using System.ComponentModel.DataAnnotations;

namespace ForExercising.ViewModels.Enums
{
    public enum MonsterType
    {
        Aqua,
        Beast,
        [Display(Name ="Beast-Warrior")]BeastWarrior,
        Cyberse,
        Dinosaur,
        [Display(Name = "Divine-Beast")] DivineBeast,
        Dragon,
        Fairy,
        Fiend,
        Fish,
        Insect,
        Machine,
        Plant,
        Psychic,
        Pyro,
        Reptile,
        Rock,
        [Display(Name = "Sea Serpent")] SeaSerpent,
        Spellcaster,
        Thunder,
        Warrior,
        [Display(Name = "Winged Beast")] WingedBeast,
        Wyrm,
        Zombie
    }
}

ForExercising/ViewModels/UserRegisterFormViewModel.cs
namespace ForExercising.ViewModels
{
    public class UserRegisterFormViewModel
    {
        public string Username { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public string ConfirmPassword { get; set; }
    }
}

ForExercising/ViewModels/ViewComponents/GetUsersInfoViewModel.cs
namespace ForExercising.ViewModels.ViewComponents
{
    public class GetUsersInfoViewModel
    {
        public string Id { get; set; }
        public string Username { get; set; }
    }
}

ForExercising/Controllers/CardsController.cs
using ForExercising.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ForExercising.Controllers
{
    public class CardsController : Controller
    {
        public IActionResult Add()
        {
            var model = new AddYuGiOhCardViewModel()
            {
                Level = 1,
                Attack = 0,
                Defense = 0,
                CreatedOn = DateTime.UtcNow
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Add(AddYuGiOhCardViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            return RedirectToAction(nameof(AddCardSuccess));
        }

        public IActionResult AddCardSuccess()
        {
            return View();
        }
    }
}

ForExercising/Controllers/HomeController.cs
using ForExercising.CustomFilters;
using ForExercising.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ForExercising.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            this.configuration = configuration;
        }

        public IActionResult Index()
        {
            this.ViewBag.ProjectName = Assembly.GetEntryAssembly().GetName().Name;

            this.ViewData["Message"] = "Current local time";
            this.ViewData["Time"] = DateTime.UtcNow.ToLocalTime().ToShortTimeString();
            return View();
        }

        public IActionResult Config()
        {
            return Content(this.configuration["ConnectionStrings:DefaultConnection"]);
        }

        public IActionResult Privacy([Required][MaxLength(10)][RegularExpression(@"[A-Za-z]+")] string name, [Range(0, 150)] int age, string[] hobbies)
        {
            if (ModelState.IsValid)
            {
                return this.Json($"My name is {name} and I am {age} years old! My hobbies are: { string.Join(", ", hobbies)}");
            }

            StringBuilder errors = new StringBuilder();

            foreach (var error in ModelState.Values.SelectMany(x => x.Errors))
            {
                errors.AppendLine(error.ErrorMessage);
            }

            return this.Json(errors.ToString());
        }

        public IActionResult StatusCodeException(int statusCode)
        {
            return View();
        }

        public IActionResult Exception()
        {
            throw new Exception();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ForExercising/ViewComponents/GetUsersInfoViewComponent.cs
using ForExercising.Data;
using ForExercising.ViewModels.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ForExercising.ViewComponents
{
    public class GetUsersInfoViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext db;

        public GetUsersInfoViewComponent(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IViewComponentResult Invoke()
        {
            var model = this.db.Users
                .Select(x => new GetUsersInfoViewModel
                {
                    Id = x.Id,
                    Username = x.UserName
                })
                .ToList();

            return this.View(model);
        }
    }
}

ForExercising/Views/Cards/Add.cshtml
@model ForExercising.ViewModels.AddYuGiOhCardViewModel
@using ForExercising.ViewModels.Enums

<h1>Add Card</h1>

<form method="post" class="col-md-6">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Attribute"></label>
        <select asp-for="Attribute" class="form-control" asp-items="@Html.GetEnumSelectList<MonsterAttribute>()"></select>
        <span asp-validation-for="Attribute" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Level"></label>
        <input asp-for="Level" class="form-control" />
        <span asp-validation-for="Level" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Artwork"></label>
        <input asp-for="Artwork" class="form-control" />
        <span asp-validation-for="Artwork" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type"></label>
        <select asp-for="Type" class="form-control" asp-items="@Html.GetEnumSelectList<MonsterType>()"></select>
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Attack"></label>
        <input asp-for="Attack" class="form-control" />
        <span asp-validation-for="Attack" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Defense"></label>
        <input asp-for="Defense" class="form-control" />
        <span asp-validation-for="Defense" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CreatedOn"></label>
        <input asp-for="CreatedOn" class="form-control" />
        <span asp-validation-for="CreatedOn" class="text-danger"></span>
    </div>
    <input type="submit" class="btn btn-primary" />
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial.cshtml" />
}

ForExercising/Views/Cards/AddCardSuccess.cshtml
<div class="alert alert-success">Card added successfuly</div>

ForExercising/Views/Home/Index.cshtml
@inject IGetUsersCountService GetUsersCountService
@model ForExercising.ViewModels.UserRegisterFormViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to @ViewBag.ProjectName</h1>
    <p>@ViewData["Message"]: @ViewData["Time"]</p>
    <p>Current users count: @GetUsersCountService.GetCount()</p>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


@section Links{
    <a href="https://youtube.com">YouTube</a>
}

@*<form asp-action="Index">
        <input asp-for="Username" />
        <input asp-for="Email" />
        <input asp-for="Password" />
        <input asp-for="ConfirmPassword" />
    </form>*@

<div class="col">
    <div class="form-group">
        <label for="Input_Username">Username</label>
        <input class="form-control" type="text" name="Input_Username" />
    </div>
    <div class="form-group">
        <label for="Input_Email">Username</label>
        <input class="form-control" type="email" name="Input_Email" />
    </div>
    <div class="form-group">
        <label for="Input_Password">Password</label>
        <input class="form-control" type="text" name="Input_Password" />
    </div>
    <div class="form-group">
        <label for="Input_ConfirmPassword">ConfirmPassword</label>
        <input class="form-control" type="text" name="Input_ConfirmPassword" />
    </div>
</div>

<partial name="_HomePartialView" />

ForExercising/Views/Home/StatusCodeException.cshtml
<p>Error</p>
<img src="https://softuni.bg/Content/images/404animation.gif" />

ForExercising/Views/Shared/Components/GetUsersInfo/Default.cshtml
@model IEnumerable<ForExercising.ViewModels.ViewComponents.GetUsersInfoViewModel>

@{ int i = 1;}

<table class="table table-bordered table-dark">
    <tr>
        <td>#</td>
        <td>Id</td>
        <td>Username</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@(i++)</td>
            <td>@item.Id</td>
            <td>@item.Username</td>
        </tr>
    }
</table>

ForExercising/Views/Shared/_HomePartialView.cshtml
<article class="col-3">
    <h2>Google Chrome</h2>
    <p>Google Chrome is a web browser developed by Google, released in 2008. Chrome is the world's most popular web browser today!</p>
</article>

<a href="https://google.com" class="btn btn-primary">Go to Google</a>

ForExercising/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ForExercising</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ForExercising</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <vc:get-users-info />
            @RenderSection("Links", false)
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ForExercising - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>